#!/usr/bin/env python3
"""One-time cleanup of wrongly excluded job triage from Sep 29-30, 2026.

The database belongs to the user's Ubuntu environment. Run there after
pulling the title/work-format-only triage changes.

Default: preview ONLY. To delete, pass --execute. Every deleted row is
backed up locally as JSON (file permissions 0600) before the transaction
commits. Do not commit backups to GitHub.
"""
from __future__ import annotations

import argparse
from datetime import datetime
import json
import os
from pathlib import Path
import sys
from uuid import uuid4
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import queue_service  # noqa: E402


# Last night (September 29 from 18:00 Berlin time) and all September 30.
BERLIN = ZoneInfo("Europe/Berlin")
START = datetime(2026, 9, 29, 18, 0, tzinfo=BERLIN)
END = datetime(2026, 10, 1, 0, 0, tzinfo=BERLIN)

# Only triage statuses generated by the filtering logic. Never delete
# applications, ready_for_review, processing, pending or done rows.
WHERE = """
    created_at >= %s AND created_at < %s
    AND (
        (status = 'discarded' AND rejected_reason IS NOT NULL)
        OR (
            status = 'failed'
            AND (job_text IS NOT NULL OR work_format IS NOT NULL)
        )
    )
"""


def _serialize(value):
    if isinstance(value, (datetime,)):
        return value.isoformat()
    return str(value)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--execute", action="store_true",
        help="Delete eligible rows after saving a local backup. Default: preview only.",
    )
    args = parser.parse_args()

    with queue_service.get_conn() as conn:
        with conn.cursor(cursor_factory=queue_service.psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM job_queue WHERE " + WHERE
                + " ORDER BY created_at, job_url FOR UPDATE",
                (START, END),
            )
            rows = [dict(r) for r in cur.fetchall()]
            counts = {}
            for row in rows:
                key = (row["status"], row.get("rejected_reason") or row.get("last_error") or "")
                counts[key] = counts.get(key, 0) + 1

            print(f"Window: {START.isoformat()} to {END.isoformat()} (exclusive)")
            print(f"Eligible triage rows: {len(rows)}")
            for (status, reason), count in sorted(counts.items()):
                print(f"  {status:10s} {count:5d} {reason[:100]}")
            if not rows:
                print("Nothing to reset.")
                return

            if not args.execute:
                print("PREVIEW ONLY. Re-run with --execute to back up and delete.")
                return

            # Save a complete, reusable backup BEFORE committing deletion.
            backup_dir = ROOT / "maintenance_backups"
            backup_dir.mkdir(mode=0o700, exist_ok=True)
            name = (
                "triage-reset-20260929-30-"
                + datetime.now(BERLIN).strftime("%Y%m%d-%H%M%S")
                + "-" + uuid4().hex[:8] + ".json"
            )
            backup = backup_dir / name
            flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
            fd = os.open(backup, flags, 0o600)
            try:
                with os.fdopen(fd, "w", encoding="utf-8") as f:
                    json.dump(rows, f, default=_serialize, indent=2, ensure_ascii=False)
                    f.flush()
                    os.fsync(f.fileno())
            except Exception:
                backup.unlink(missing_ok=True)
                raise

            ids = [row["id"] for row in rows]
            cur.execute(
                "DELETE FROM job_queue WHERE id = ANY(%s::uuid[]) AND ("
                + WHERE + ") RETURNING id",
                (ids, START, END),
            )
            deleted = cur.rowcount
            if deleted != len(rows):
                raise RuntimeError(
                    f"Expected {len(rows)} rows but deleted {deleted}; rolled back."
                )
            # The context manager commits on success, otherwise rolls back.
            print(f"Deleted {deleted} triage rows. Backup: {backup}")
            print("Re-run the LinkedIn searches to discover these URLs again.")


if __name__ == "__main__":
    main()
